---
title: "Are LIHTC projects becoming more integrative?"
author: "Colin Ries"
header-includes:
- \usepackage{booktabs}
- \usepackage{siunitx}
- \newcolumntype{d}{S[input-symbols = ()]}
output:
  slidy_presentation: default
  html_notebook: default
  pdf_document: default
---

```{r setup, include=FALSE}

knitr::opts_chunk$set(warning=FALSE)

```

# Introduction

Measuring a program impact

- Evolving legal landscape
- Changing federal policies
- Shifting administrative priorities
- Public and elite attitudes


---

# Data & Methods

```{r packages}

library(tidyverse)
library(haven)

```


```{r import_data}
# Load National LIHTC data
lihtc <- read_csv('../data/LIHTCPUB.CSV')

lihtc <- lihtc %>% 
  filter(yr_alloc <= 2019)

```
---
# Data & Methods
## Examining Data Quality

```{r data_quality}

# Normalize the values for QCT and DDA
lihtc <- lihtc %>% 
  mutate(qct = 0+ 1*(qct==1)) %>% 
  # Do not distinguish between metro, non-metro, and gulf opportunity zone DDAs
  mutate(dda = 1*(dda!=0))

# lihtc_ca <- lihtc_ca %>% 
lihtc_ca <- lihtc %>% 
  #filter(yr_alloc <= 2018) %>% 
  filter(proj_st == 'CA') 

# Calculate the number of projects allocated credits by year
ggplot(mapping = aes(x=yr_alloc)) +
  #geom_freqpoly(data = lihtc) +
  geom_freqpoly(data = lihtc_ca)

# Calculate the total number of low-income units for each allocation year
li_units_ca <- lihtc_ca %>% 
  group_by(yr_alloc) %>% 
  summarise(y = sum(li_units, na.rm=TRUE))

ggplot(data = li_units_ca, mapping = aes(x=yr_alloc, y=y)) +
  geom_line()


```
---
# De-concentrating Poverty

```{r qct}

qct_sites <- lihtc %>% 
  group_by(proj_st, yr_alloc) %>%
  summarise(y=mean(qct, na.rm = TRUE))

# Calculate the proportion of California LIHTC projects in QCTs
ca_qcts <- qct_sites %>% 
  filter(proj_st == "CA") %>% 
  group_by(yr_alloc) %>% 
  summarise(y=mean(y, na.rm = TRUE))

# Calculate the proportion of all other LIHTC projects in QCTs
us_qcts <- qct_sites %>%
  filter(proj_st != "CA") %>%
  group_by(yr_alloc) %>% 
  summarise(y=mean(y, na.rm = TRUE))

comp_qcts <- ca_qcts %>% 
  inner_join(us_qcts,by="yr_alloc") %>% 
  filter((yr_alloc <= 2019)&(yr_alloc >= 2003))

ggplot(data = comp_qcts) +
  geom_line(mapping = aes(yr_alloc, y.x, color = "green")) +
  geom_line(mapping = aes(yr_alloc, y.y))

```
---
# Affordable Housing in Affluent Areas

```{r dda}

dda_sites <- lihtc %>%
  filter(yr_alloc >= 2003) %>% 
  mutate(dda = 1*(dda!=0)) %>%
  group_by(proj_st, yr_alloc) %>%
  summarise(y=mean(dda, na.rm = TRUE))

ca_dda <- dda_sites %>% 
  filter(proj_st == "CA") %>% 
  group_by(yr_alloc) %>% 
  summarise(y=mean(y, na.rm = TRUE))

us_dda <- dda_sites %>%
  filter(proj_st != "CA") %>%
  group_by(yr_alloc) %>% 
  summarise(y=mean(y, na.rm = TRUE))

comp_dda <- ca_dda %>% 
  inner_join(us_dda,by="yr_alloc") %>% 
  filter((yr_alloc <= 2019)&(yr_alloc >= 2003))

ggplot(data = comp_dda) +
  geom_line(mapping = aes(yr_alloc, y.x, color = "green")) +
  geom_line(mapping = aes(yr_alloc, y.y))
```

---
# Mixed Income Developments

```{r inclusiveness}

mixed_income <- lihtc %>% 
  filter(n_units >0) %>% 
  mutate(inclusiveness = li_units/n_units) %>% 
  group_by(proj_st, yr_alloc) %>% 
  summarise(y=mean(inclusiveness, na.rm = TRUE, inf.rm = TRUE))

mixed_income_ca <- mixed_income %>% 
  filter(proj_st == "CA") %>% 
  group_by(yr_alloc) %>% 
  summarise(y=mean(y, na.rm = TRUE, inf.rm = TRUE))

mixed_income_us <- mixed_income %>% 
  filter(proj_st != "CA") %>% 
  group_by(yr_alloc) %>% 
  summarise(y=mean(y, na.rm = TRUE, inf.rm = TRUE))

comp_mi <- mixed_income_ca %>% 
  inner_join(mixed_income_us,by="yr_alloc") %>% 
  filter((yr_alloc <= 2019))

ggplot(data = comp_mi) +
  geom_line(mapping = aes(yr_alloc, y.x, color = "green")) +
  geom_line(mapping = aes(yr_alloc, y.y))

```

